### ISSUE TITLE
The app crashes when playing music from a playlist

### ISSUE THREAD

**Issue by Lohita9** [khaled-0/TubeSync#11]
Crash log:![Screenshot_2024-11-30-05-02-19-125_com miui bugreport](https://github.com/user-attachments/assets/cb6692b5-5b96-4b86-9c42-ef16fde02cf8)

Video: https://github.com/user-attachments/assets/b4fc9aea-c4e3-4532-864b-f5a44aee356e

After this error, the TubeSync notification cannot be cleared when I try to dismiss it.

Version: latest nightly build
Android version: 11

**Comment by khaled-0** [comment]
hi, please try the latest nightly

**Comment by khaled-0** [comment]
> This issue has been fixed, but another issue arises: while playing a song from a playlist and then exiting, the song continues to play, but no notification is displayed.

I can't reproduce the issue, please make sure you have notification permissions enabled, also enabled auto start on your device as it's a Xiaomi specific thing
