### ISSUE TITLE
Shuffle doesn't shuffle

### ISSUE THREAD

**Issue by doonoo** [khaled-0/TubeSync#12]
When I click the shuffle button, it'll just go to a random song in the list and just keep playing in order from where it started at. It's suppose to shuffle the whole playlist and play it from the beginning.

**Comment by khaled-0** [comment]
Well I purposefully keep the currently playing song at the top of queue
the rest of playlist are shuffled.

**Comment by khaled-0** [comment]
could you try the latest nightly build and let me know

**Comment by doonoo** [comment]
Yeah sorry, got distracted this week. But shuffle does work so far. Thank you sir.
