### ISSUE TITLE
Feature Request: Sleep Timer

### ISSUE THREAD

**Issue by ilker-binzet** [khaled-0/TubeSync#15]
### Feature Request: Sleep Timer

**Summary**
Add a sleep timer feature to automatically stop media playback after a set duration. Users can choose from preset intervals of 15, 30, 60 minutes, or set a custom duration.

**Use Case**
Users may want to listen to music or watch videos before sleeping or need the media to stop automatically after a specific duration. The sleep timer will automatically stop playback after the selected time period.

**Proposed Solution**
- Add a timer button to the media player interface
- Preset duration options:
  - 15 minutes
  - 30 minutes
  - 60 minutes
- Custom duration option
- Small indicator showing remaining time

**Benefits**
- Battery conservation
- Enhanced user experience
- Perfect for bedtime usage
- Prevents unnecessary media playback

**Example Flow**
1. User starts media playback
2. Taps the timer button
3. Selects from preset durations or sets custom time
4. Media automatically stops when timer expires

**Additional Notes**
The timer interface should be easily accessible and provide visual feedback of the remaining time. When the timer is active, users should be able to modify or cancel it as needed.

**Comment by khaled-0** [comment]
Implemented in 2b91eb6

![Screenshot From 2024-12-16 20-35-30](https://github.com/user-attachments/assets/ba3fc468-aefd-41d2-8b8f-a18917c7ade8)
![Screenshot From 2024-12-16 20-35-18](https://github.com/user-attachments/assets/b67780cf-5d5c-44f1-98e0-be13a56e06dc)
