### ISSUE TITLE
Music Wraps Around and Plays for a Split Second Before Transitioning to Next Track

### ISSUE THREAD

**Issue by iyxan23** [khaled-0/TubeSync#3]
I'm using the Flatpak version on Linux and I noticed a small bug: when a song ends, it starts playing again for 1-3 seconds before the next song starts. Not sure how this happened, it might be related to the fact that I haven't downloaded the entire playlist yet.

Here's a simpler breakdown:

 - Play a song (Song A).
 - Wait for Song A to end.
 - Notice that Song A starts playing again for 1-3 seconds.
 - Song A stops, and Song B starts.

**Comment by khaled-0** [comment]
Hi, thanks for reporting.
I was able to replicate the issue, will be fixed on next release.
meanwhile maybe try using latest nightly build if you may.

**Comment by iyxan23** [comment]
That's some quick draw!

<img src="https://media1.tenor.com/m/_qKEXLluLvQAAAAd/clint-eastwood-draw.gif" />
