### ISSUE TITLE
Mix playlist

### ISSUE THREAD

**Issue by doonoo** [khaled-0/TubeSync#6]
Can you make it to where multiple playlists can be added to one playlist.

**Comment by khaled-0** [comment]
Well playlists are synced with YouTube, but what I might do is add an option to queue multiple playlists while playing. Would that work?

**Comment by doonoo** [comment]
Yes, something like that. Having multiple playlist in one queue where it can be shuffle.

**Comment by doonoo** [comment]
Yes, something like that. Having multiple playlist in one queue where it can be shuffled.

**Comment by doonoo** [comment]
Yes, something like that. Having multiple playlist in one queue where it can be shuffled.

**Comment by doonoo** [comment]
Yes, something like that. Having multiple playlist in one queue where it can be shuffled.

**Comment by khaled-0** [comment]
Implemented in https://github.com/khaled-0/TubeSync/commit/881697395286e843b57095dbaca43f6749bfb0f2

Please try latest nightly build or wait for release

**Comment by doonoo** [comment]
Thank you!
