### ISSUE TITLE
[Feature Request]  Adding Playlists via Share Intent

### ISSUE THREAD

**Issue by justpanchi** [khaled-0/TubeSync#7]
## Summary  
Enable the ability to add playlists to the app using the "Share" feature from other apps, such as YouTube. This would streamline the process of importing playlists by eliminating the need to manually copy and paste URLs.  

## Use Case  
Currently, users need to open the app, tap the "+" button, and manually paste a playlist URL. Adding support for handling shared URLs would allow users to seamlessly send a playlist URL to the app directly from the YouTube app or browser.  

## Proposed Solution  
Implement an intent handler that captures shared links matching the format of supported playlist URLs. When the user shares a playlist (e.g., via the YouTube app), the app should recognize the playlist URL and automatically import it.  

## Benefits  
- Improved user experience by simplifying the process of adding playlists.  
- Faster workflow for importing content.    

## Example Flow  
1. A user browses a playlist in the YouTube app.  
2. They tap the "Share" button and select the app from the list of share targets.  
3. The app opens (or processes the intent in the background) and automatically adds the playlist to the library.  

## Additional Notes  
If necessary, the app could display a confirmation dialog before adding the playlist, or show a toast/notification confirming the successful addition.

**Comment by khaled-0** [comment]
try latest nightly as new release is gonna be latw
