### ISSUE TITLE
Remove the forward/rewind 5 sec buttons in the notification player

### ISSUE THREAD

**Issue by fessmm** [khaled-0/TubeSync#9]
Hi, can you remove the forward/rewind buttons or at least give the ability to remove them via a setting maybe? 
i dont think anyone uses those in the notifications player when you can literally drag the the slider where you want. thanks.

**Comment by khaled-0** [comment]
what would you prefer instead? jusk gathering opinion

**Comment by fessmm** [comment]
IMO just play/pause and previous/next is enough, but i wouldnt mind if the shuffle and repeat button is also visible.

basically in this order: shuffle, previous, play/pause, next, repeat

or really basic: basically in this order: previous, play/pause, next

**Comment by khaled-0** [comment]
implemented on latest nightly build 
will be in next release

**Comment by fessmm** [comment]
Tested the nightly build. There is no repeat button.

also the new notification buttons are now misaligned. play/pause button should always be centered in the notification player.

**Comment by fessmm** [comment]
New version:
![grafik](https://github.com/user-attachments/assets/ea56b2af-7ec0-4051-a9d8-8f2904f08274)
Old version:
![grafik](https://github.com/user-attachments/assets/e8722686-abf8-4b23-ad4b-55679976933e)

**Comment by khaled-0** [comment]
Could you try https://github.com/khaled-0/TubeSync/actions/runs/12088181860 and report

**Comment by fessmm** [comment]
Better now, but its bugged for the first song of the playlist

**Comment by khaled-0** [comment]
> Tested the latest build, still same bug with the first song in the notification player Can you just force the one view everytime? shuffle, previous, play/pause, next, repeat

what bug exactly?

**Comment by fessmm** [comment]
![grafik](https://github.com/user-attachments/assets/66d41ab8-ac1c-432f-bfe1-655aba2cc67e)

**Comment by fessmm** [comment]
it should always be like this

![grafik](https://github.com/user-attachments/assets/8219c3aa-cdd1-41b9-8035-c71bf1963cb2)

**Comment by khaled-0** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/19999039/391262203-66d41ab8-ac1c-432f-bfe1-655aba2cc67e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMjgyNDAsIm5iZiI6MTczMzAyNzk0MCwicGF0aCI6Ii8xOTk5OTAzOS8zOTEyNjIyMDMtNjZkNDFhYjgtYWMxYy00MzJmLWJmZTEtNjU1YWJhMmNjNjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDA0MzkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZGFmMWFiNDVhZGZlN2ZmNzY3ZDc0MmEwODNmMGRlMTg2ODg2YWFlMmQ3ZGY1Y2M3Y2MyMmNiYTEwYmE1NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5r5uyMZarjMTvqRfXCRRnXmCJRqUAyFvtcawEsJSwT8)

this is the intended behavior. you don't need the previous/next button when you don't have previous/next entries.

**Comment by fessmm** [comment]
Yeah but it messes up the alignment

**Comment by khaled-0** [comment]
> Yeah but it messes up the alignment

Yeah idk why the repeat goes to start. out of flutter's control sp, maybe just deal with it for now.

Try the new release btw

**Comment by fessmm** [comment]
Can you atleast give me this option then pls?

previous, play/pause, next

**Comment by fessmm** [comment]
@khaled-0  nah, im sorry but the notification player buttons look so ugly for the first song. Please fix that 😁

**Comment by fessmm** [comment]
Perfect. Thank you!

**Comment by fessmm** [comment]
Uhhh.. now the prev button is missing for the first song of the playlist.. and the next button for the last song..

Any chance to force them to be always there? For example when im on the first song and i press "prev" it should play the song again.
And when im on the last song of the playlist and i press "next" it should go to the first song of the playlist.

Any chance for that?

**Comment by fessmm** [comment]
Also what happened to the slider? Its not working for me. There is no option to drag and drop it to another position

**Comment by khaled-0** [comment]
Hi, try this https://github.com/khaled-0/TubeSync/actions/runs/12133512201
If your loop mode is on then the expected icons will always show

**Comment by fessmm** [comment]
Thanks! Its working perfectly fine now
